spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:sqlserver://learning-spring-apps.database.windows.net:1433;database=learning-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: charan
    password: Varun2005@
